server:
  port: 8001 #端口号

spring:
  application:
    name: mcroservice-payment
  datasource:
    url: jdbc:mysql://121.89.235.200:3306/mysql?useUnicode=true&characterEncoding=utf8&userSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*mapper.xml # Mybatis 映射文件位置
  type-aliases-package: com.ncc.demo.entity  # 表对应的实体类包

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      defaultZone: http://localhost:7001/eureka